apiVersion: v1
kind: Service
metadata:
  name: create
spec:
  ports:
    - port: 8081
      targetPort: 8080
  selector:
    app: create
---
apiVersion: v1
kind: Service
metadata:
  name: update
spec:
  ports:
    - port: 8082
      targetPort: 8080
  selector:
    app: update
---
apiVersion: v1
kind: Service
metadata:
  name: delete
spec:
  ports:
    - port: 8083
      targetPort: 8080
  selector:
    app: delete
---
apiVersion: v1
kind: Service
metadata:
  name: search
spec:
  ports:
    - port: 8084
      targetPort: 8080
  selector:
    app: search
---
apiVersion: v1
kind: Service
metadata:
  name: search
spec:
  ports:
    - port: 8085
      targetPort: 8080
  selector:
    app: search
